# Site Settings
title: AdvoAdvice Rechtsanwälte mbB - Rechtsberatung online und deutschlandweit
email: info@advoadvice.com
keywords: AdvoAdvice, Rechtsanwälte, Berlin, Partnerschaft, Rechtsberatung, Tintemann, Klevenhagen, Bankrecht, Kapitalmarktrecht, Datenschutz, Verbraucherschutz, Schufa-Recht, Immobilienrecht, Kreditrecht
description: Kompetente Rechtsberatung von erfahrenen Rechtsanwälten und Fachanwälten für Ihren Erfolg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://advoadvice.de" # the base hostname & protocol for your site

# Collection Settings
collections:
  team_members:
    output: true
  topics:
    output: true
    permalink: /themen/:path/
  posts:
    permalink: /blog/:title/

# Content Defaults
defaults:
  -
    scope:
      path: "_topics" # empty string for all files
    values:
      layout: "topic"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include:
  - _redirects # Netlify Redirects
exclude:
  - Gemfile
  - Gemfile.lock


# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-autoprefixer
  - jekyll-compress-images

paginate: 6
paginate_path: "/blog/page:num/"

autoprefixer:
  browsers:
    - "last 2 versions"
    - "IE > 9"
compress_images:
  images_path: "uploads/**/*.{gif,png,jpg,jpeg,svg}"
imageoptim:
  svgo: false
  verbose: false