# Site & Meta Details (Fallback)
title: AdvoAdvice Rechtsanwälte mbB - Rechtsberatung online und deutschlandweit
description: Kompetente Rechtsberatung von erfahrenen Rechtsanwälten und Fachanwälten für Ihren Erfolg
keywords: AdvoAdvice, Rechtsanwälte, Berlin, Partnerschaft, Rechtsberatung, Tintemann, Klevenhagen, Bankrecht, Kapitalmarktrecht, Datenschutz, Verbraucherschutz, Schufa-Recht, Immobilienrecht, Kreditrecht
logo: /uploads/images/logo-compact.png

lang: de_DE
email: info@advoadvice.com
url: "https://advoadvice.de" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Collection Settings
collections:
  authors:
    output: false
  topics:
    output: true
    permalink: /themen/:path/
  posts:
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ''
      # type: ''
    values:
      _comments:
        title: Der Titel ist wichtig für SEO, sollte für jede Seite anders und 40 - 65 Zeichen lang sein.
        description: Die kurze Beschreibung ist wichtig für SEO und ist idealerweise 100 - 156 Zeichen lang. 

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include:
  - _redirects # Netlify Redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - siteicon.png


# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
  # - jekyll-redirect-from
  # - jekyll-compress-images # activate periodically to compress all images
  # - jekyll/tagging
  # - jekyll-tagging-related_posts

  # Custom plugins in _plugins folder are: 
  # - suggested_posts: filter used to display 3 posts related to the given one

paginate: 6
paginate_path: "/blog/page-:num/"
seo_paginator_message: "Blog Seite %{current} von %{total} | "

autoprefixer:
  browsers:
    - "last 2 versions"
    - "IE > 9"
# compress_images:
#   images_path: "uploads/**/*.{gif,png,jpg,jpeg,svg}"
# imageoptim:
#   svgo: false
#   verbose: false