# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AdvoAdvice Rechtsanwälte mbB - Rechtsberatung online und deutschlandweit
email: your-email@domain.com
keywords: AdvoAdvice, Rechtsanwälte, Berlin, Partnerschaft, Rechtsberatung, Tintemann, Klevenhagen, Bankrecht, Kapitalmarktrecht, Datenschutz, Verbraucherschutz, Schufa-Recht, Immobilienrecht, Kreditrecht
description: Kompetente Rechtsberatung von erfahrenen Rechtsanwälten und Fachanwälten für Ihren Erfolg
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

collections:
  team_members:
    output: true
  topics:
    output: true
    permalink: /themen/:path/
  posts:
    permalink: /blog/:title/

# Default settings
defaults:
  -
    scope:
      path: "_topics" # empty string for all files
    values:
      layout: "page"
      
# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-paginate
  # - jekyll-related-posts

paginate: 6
paginate_path: "/blog/page:num/"
related:
  max_count: 3
